In [1]:
from __future__ import print_function, division
from builtins import range


In [5]:
# Note: you may need to update your version of future
# sudo pip install -U future


import numpy as np
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
import pandas as pd



In [9]:

# load the data
X = []
Y = []
for line in open('Book4.csv'):
    x1, x2, y = line.split(',')
    X.append([float(x1), float(x2), 1])
    Y.append(float(y))


In [15]:
X=np.array(X)

In [16]:
Y=np.array(Y)

In [17]:
X.shape

(100, 3)

In [18]:
Y.shape

(100,)

In [19]:
X.T.shape

(3, 100)

In [21]:
np.dot(X.T, X)

array([[3.17964461e+05, 2.66945098e+05, 4.79777936e+03],
       [2.66945098e+05, 4.07047675e+05, 5.62712840e+03],
       [4.79777936e+03, 5.62712840e+03, 1.00000000e+02]])

In [22]:
np.dot(X.T, Y)

array([1441029.69356773, 1755436.72133404,   26533.44903201])

In [23]:
w = np.linalg.solve(np.dot(X.T, X), np.dot(X.T, Y))
Yhat = np.dot(X, w)

In [26]:
w

array([2.01666793, 2.96985048, 1.46191241])

In [24]:
Yhat.shape

(100,)

In [27]:
d1 = Y - Yhat
d2 = Y - Y.mean()
r2 = 1 - d1.dot(d1) / d2.dot(d2)
print("the r-squared is:", r2)

the r-squared is: 0.9980040612427971
