In [1]:
from __future__ import print_function, division
from builtins import range




import numpy as np

N = 100
D = 2

In [2]:
X = np.random.randn(N,D)

In [5]:
X

array([[-1.38944384e+00,  3.15558742e-01],
       [ 1.18937519e+00,  1.40441491e+00],
       [-1.48284111e+00, -2.30893793e+00],
       [ 1.90735584e-01,  2.85248497e-01],
       [-5.34594336e-01,  1.03433020e+00],
       [-5.86380782e-01, -7.32276127e-01],
       [-2.01839142e+00, -7.16616081e-01],
       [ 4.14648474e-02, -2.03888467e+00],
       [ 1.41031544e-02,  1.17967243e+00],
       [-7.66877981e-01,  2.06079906e-01],
       [ 4.29022542e-01,  1.07119084e+00],
       [ 3.51330854e-01, -1.41639619e-01],
       [-6.87592008e-01, -1.45126160e+00],
       [ 1.20961105e+00,  9.10971109e-01],
       [-1.89649282e+00, -5.47009099e-01],
       [ 2.67821065e-01, -1.27903186e+00],
       [ 5.84928027e-01,  4.16495496e-01],
       [-1.69335813e+00,  5.86033149e-01],
       [ 6.72711342e-01, -2.07218790e-02],
       [-6.73441619e-01,  9.55234952e-01],
       [-2.32744698e-01,  4.78084506e-01],
       [-1.24573499e+00,  5.26029927e-01],
       [-6.42541449e-01, -2.96285475e-01],
       [ 1.

In [6]:
# center the first 50 points at (-2,-2)
X[:50,:] = X[:50,:] - 2*np.ones((50,D))

# center the last 50 points at (2, 2)
X[50:,:] = X[50:,:] + 2*np.ones((50,D))

In [7]:
X

array([[-3.38944384, -1.68444126],
       [-0.81062481, -0.59558509],
       [-3.48284111, -4.30893793],
       [-1.80926442, -1.7147515 ],
       [-2.53459434, -0.9656698 ],
       [-2.58638078, -2.73227613],
       [-4.01839142, -2.71661608],
       [-1.95853515, -4.03888467],
       [-1.98589685, -0.82032757],
       [-2.76687798, -1.79392009],
       [-1.57097746, -0.92880916],
       [-1.64866915, -2.14163962],
       [-2.68759201, -3.4512616 ],
       [-0.79038895, -1.08902889],
       [-3.89649282, -2.5470091 ],
       [-1.73217894, -3.27903186],
       [-1.41507197, -1.5835045 ],
       [-3.69335813, -1.41396685],
       [-1.32728866, -2.02072188],
       [-2.67344162, -1.04476505],
       [-2.2327447 , -1.52191549],
       [-3.24573499, -1.47397007],
       [-2.64254145, -2.29628548],
       [-1.89797224, -0.75721967],
       [-0.73262984, -1.64686446],
       [-0.61086297, -1.45455344],
       [-2.24525122, -0.80816188],
       [-1.68366662, -1.96863727],
       [-3.23161113,

In [8]:
T = np.array([0]*50 + [1]*50)

In [9]:
T

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [12]:
ones = np.ones((N, 1))
#ones
Xb = np.concatenate((ones, X), axis=1)

In [13]:
Xb

array([[ 1.        , -3.38944384, -1.68444126],
       [ 1.        , -0.81062481, -0.59558509],
       [ 1.        , -3.48284111, -4.30893793],
       [ 1.        , -1.80926442, -1.7147515 ],
       [ 1.        , -2.53459434, -0.9656698 ],
       [ 1.        , -2.58638078, -2.73227613],
       [ 1.        , -4.01839142, -2.71661608],
       [ 1.        , -1.95853515, -4.03888467],
       [ 1.        , -1.98589685, -0.82032757],
       [ 1.        , -2.76687798, -1.79392009],
       [ 1.        , -1.57097746, -0.92880916],
       [ 1.        , -1.64866915, -2.14163962],
       [ 1.        , -2.68759201, -3.4512616 ],
       [ 1.        , -0.79038895, -1.08902889],
       [ 1.        , -3.89649282, -2.5470091 ],
       [ 1.        , -1.73217894, -3.27903186],
       [ 1.        , -1.41507197, -1.5835045 ],
       [ 1.        , -3.69335813, -1.41396685],
       [ 1.        , -1.32728866, -2.02072188],
       [ 1.        , -2.67344162, -1.04476505],
       [ 1.        , -2.2327447 , -1.521

In [14]:
w = np.random.randn(D + 1)

In [15]:
w

array([-1.20340221,  0.3666083 , -0.57546686])

In [16]:
Xb.shape

(100, 3)

In [17]:
w.shape

(3,)

In [20]:
z = Xb.dot(w)

In [22]:
z.shape

(100,)

In [23]:
def sigmoid(z):
    return 1/(1 + np.exp(-z))



In [24]:
Y = sigmoid(z)

In [25]:
Y.shape

(100,)

In [29]:
Y

array([0.18593239, 0.23905917, 0.49985258, 0.29319624, 0.17123574,
       0.35910369, 0.24726449, 0.59936664, 0.18856261, 0.23407887,
       0.22359521, 0.35999741, 0.4495203 , 0.29599033, 0.23754806,
       0.51213281, 0.30769342, 0.14884017, 0.37118447, 0.17047276,
       0.24119611, 0.17579588, 0.29927688, 0.18793873, 0.37185326,
       0.35656549, 0.17343731, 0.33453092, 0.16548916, 0.13521659,
       0.07226092, 0.4613087 , 0.3262685 , 0.60638048, 0.48844251,
       0.27514033, 0.20666225, 0.1934787 , 0.14384732, 0.13808938,
       0.28771443, 0.13892657, 0.26158941, 0.30880921, 0.29557585,
       0.25828217, 0.42978442, 0.14876107, 0.34442822, 0.20358767,
       0.15275597, 0.27648214, 0.0720513 , 0.11425423, 0.49349377,
       0.13555645, 0.0917923 , 0.11392222, 0.11475563, 0.1064088 ,
       0.10942141, 0.11143611, 0.22039512, 0.09401311, 0.0610128 ,
       0.10787793, 0.21712942, 0.22170485, 0.44946157, 0.0769383 ,
       0.27076055, 0.2281633 , 0.20754636, 0.05904766, 0.12281

In [26]:
def cross_entropy(T, Y):
    E = 0
    for i in range(len(T)):
        if T[i] == 1:
            E -= np.log(Y[i])
        else:
            E -= np.log(1 - Y[i])
    return E

In [30]:
print(cross_entropy(T, Y))

107.846819039413


In [32]:
w = np.array([0, 4, 4])
z = Xb.dot(w)
Y = sigmoid(z)

In [33]:
print(cross_entropy(T, Y))

0.02354590500196028
